server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: medicine-inventory-service
          uri: lb://MEDICINE-INVENTORY-SERVICE
          predicates:
            - Path=/api/medicines/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true 